[package]
name = "task1"
version = "0.1.0"
authors = ["Denis Kolodin <denis.kolodin@xdev.re>"]

[dependencies]
log = "0.3.8"
pretty_env_logger = "0.1.1"
clap = "2.26.2"
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
futures = "0.1.16"
tokio-core = "0.1.9"
